//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Metadata.Edm;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Reflection.Emit;
    using System.Security.Permissions;

    public partial class StoreEntities : DbContext
    {
        public StoreEntities()
            : base("name=StoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }

        public void showAllProducts()
        {
            Console.WriteLine("--------------------------------------------------------------------------------------------------");
            Console.WriteLine("|{0,-5}|{1,-20}|{2,-20}|{3,-20}|", "ID", "Name", "Price", "Quantity");
            Console.WriteLine("--------------------------------------------------------------------------------------------------");
            Products.ToList().ForEach(p => {
                Console.WriteLine("|{0,-5}|{1,-20}|{2,-20}|{3,-20}|", p.Id, p.Name, p.Price, p.QuantityAvailable);
            });
            Console.WriteLine("--------------------------------------------------------------------------------------------------");
        }

        public void getProductDetails()
        {
            Console.WriteLine("Enter the id of product");
            int id = Convert.ToInt32(Console.ReadLine());
            var product = Products.Find(id);
            Console.WriteLine("--------------------------------------------------------------------------------------------------");
            Console.WriteLine("|{0,-5}|{1,-20}|{2,-20}|{3,-20}|", "ID", "Name", "Price", "Quantity");
            Console.WriteLine("--------------------------------------------------------------------------------------------------");
            Console.WriteLine("|{0,-5}|{1,-20}|{2,-20}|{3,-20}|", product.Id, product.Name, product.Price, product.QuantityAvailable);
            Console.WriteLine("--------------------------------------------------------------------------------------------------");
        }

        public void buyProduct()
        {
            showAllProducts();
            Console.WriteLine("Select the product");
            int id = Convert.ToInt32(Console.ReadLine());
            Product p = Products.Find(id);
            Label:
                Console.WriteLine("Enter the quantity");
                int qnt = Convert.ToInt32(Console.ReadLine());
                if(qnt > Products.Find(id).QuantityAvailable)
                {
                    Console.WriteLine($"Please reduce you quantity. (Max = {Products.Find(id).QuantityAvailable})");
                    goto Label;
                }
            p.QuantityAvailable -=  qnt;
            SaveChanges();
            Console.WriteLine($"You have purchased {qnt} {p.Name} successfully");
        }

        public void addIntoExestingStock()
        {
            showAllProducts();
            Console.WriteLine("Select which product you want to add : ");
            int id = Convert.ToInt32(Console.ReadLine());
            Product p = Products.Find(id);
            Console.WriteLine("Enter the quantity of the product you want to add : ");
            int qnt = Convert.ToInt32(Console.ReadLine());
            p.QuantityAvailable += qnt;
            SaveChanges();
            Console.WriteLine("Product added successfully");
        }

        public void addNewStock() 
        {
            Console.WriteLine("Enter the name of product");
            string name = Console.ReadLine();

            Console.WriteLine("Enter the quantity of product");
            int qnt = Convert.ToInt32(Console.ReadLine());

            Console.WriteLine("Enter the price of product");
            int price = Convert.ToInt32(Console.ReadLine());

            Product p = new Product();
            p.Name = name;
            p.Price = price;
            p.QuantityAvailable = qnt;

            Products.Add(p);
            SaveChanges();
            Console.WriteLine("Product Added successfylly");
        }

        public void removeProduct()
        {
            showAllProducts();
            Console.WriteLine("Select which product you want to remove : ");
            int id = Convert.ToInt32(Console.ReadLine());
            Product p = Products.Find(id);
            Products.Remove(p);
            SaveChanges();
        }
    }
}
