//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Assignment1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class practiceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new practiceEntities object using the connection string found in the 'practiceEntities' section of the application configuration file.
        /// </summary>
        public practiceEntities() : base("name=practiceEntities", "practiceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new practiceEntities object.
        /// </summary>
        public practiceEntities(string connectionString) : base(connectionString, "practiceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new practiceEntities object.
        /// </summary>
        public practiceEntities(EntityConnection connection) : base(connection, "practiceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<employee> employees
        {
            get
            {
                if ((_employees == null))
                {
                    _employees = base.CreateObjectSet<employee>("employees");
                }
                return _employees;
            }
        }
        private ObjectSet<employee> _employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemployees(employee employee)
        {
            base.AddObject("employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="practiceModel", Name="employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new employee object.
        /// </summary>
        /// <param name="emp_ID">Initial value of the emp_ID property.</param>
        /// <param name="emp_NAME">Initial value of the emp_NAME property.</param>
        public static employee Createemployee(global::System.Int32 emp_ID, global::System.String emp_NAME)
        {
            employee employee = new employee();
            employee.emp_ID = emp_ID;
            employee.emp_NAME = emp_NAME;
            return employee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emp_ID
        {
            get
            {
                return _emp_ID;
            }
            set
            {
                if (_emp_ID != value)
                {
                    Onemp_IDChanging(value);
                    ReportPropertyChanging("emp_ID");
                    _emp_ID = StructuralObject.SetValidValue(value, "emp_ID");
                    ReportPropertyChanged("emp_ID");
                    Onemp_IDChanged();
                }
            }
        }
        private global::System.Int32 _emp_ID;
        partial void Onemp_IDChanging(global::System.Int32 value);
        partial void Onemp_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String emp_NAME
        {
            get
            {
                return _emp_NAME;
            }
            set
            {
                Onemp_NAMEChanging(value);
                ReportPropertyChanging("emp_NAME");
                _emp_NAME = StructuralObject.SetValidValue(value, false, "emp_NAME");
                ReportPropertyChanged("emp_NAME");
                Onemp_NAMEChanged();
            }
        }
        private global::System.String _emp_NAME;
        partial void Onemp_NAMEChanging(global::System.String value);
        partial void Onemp_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEPT_NAME
        {
            get
            {
                return _DEPT_NAME;
            }
            set
            {
                OnDEPT_NAMEChanging(value);
                ReportPropertyChanging("DEPT_NAME");
                _DEPT_NAME = StructuralObject.SetValidValue(value, true, "DEPT_NAME");
                ReportPropertyChanged("DEPT_NAME");
                OnDEPT_NAMEChanged();
            }
        }
        private global::System.String _DEPT_NAME;
        partial void OnDEPT_NAMEChanging(global::System.String value);
        partial void OnDEPT_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SALARY
        {
            get
            {
                return _SALARY;
            }
            set
            {
                OnSALARYChanging(value);
                ReportPropertyChanging("SALARY");
                _SALARY = StructuralObject.SetValidValue(value, "SALARY");
                ReportPropertyChanged("SALARY");
                OnSALARYChanged();
            }
        }
        private Nullable<global::System.Int32> _SALARY;
        partial void OnSALARYChanging(Nullable<global::System.Int32> value);
        partial void OnSALARYChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="practiceModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="user_name">Initial value of the user_name property.</param>
        public static user Createuser(global::System.Int32 user_id, global::System.String user_name)
        {
            user user = new user();
            user.user_id = user_id;
            user.user_name = user_name;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value, "user_id");
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                Onuser_nameChanging(value);
                ReportPropertyChanging("user_name");
                _user_name = StructuralObject.SetValidValue(value, false, "user_name");
                ReportPropertyChanged("user_name");
                Onuser_nameChanged();
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> amount
        {
            get
            {
                return _amount;
            }
            set
            {
                OnamountChanging(value);
                ReportPropertyChanging("amount");
                _amount = StructuralObject.SetValidValue(value, "amount");
                ReportPropertyChanged("amount");
                OnamountChanged();
            }
        }
        private Nullable<global::System.Int32> _amount;
        partial void OnamountChanging(Nullable<global::System.Int32> value);
        partial void OnamountChanged();

        #endregion

    }

    #endregion

}
