//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module2_Assignment3
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_ID { get; set; }
        public string emp_NAME { get; set; }
        public string DEPT_NAME { get; set; }
        public Nullable<int> SALARY { get; set; }
    }
}
